### ISSUE TITLE
More detailed API documentation - PLEASE!

### ISSUE THREAD

**Issue by JNickVA1** [Semantics3/semantics3-csharp#1]
While I do appreciate the availability of this client library, I really need to know more about the query structure. For instance, I would like to be able to send a query with a UPC code and specify that I want multiple fields returned, such as cat_id, category, brand, size, etc. There isn't even a UPC example on this site.

I would really appreciate any help. Thank you...

**Comment by vinothgopi** [comment]
For UPC queries, you only need to change the query here:

```
// Input the UPC here
products.products_field( "upc", "019283746548" );

// Make the query
JObject hashProducts = products.get_products();

// View the results of the query
Console.Write(hashProducts.ToString());
```

The c# library is just a wrapper to build the JSON object and make a oauth request to our API.

More information on querying can be found in [the documentation](http://docs.semantics3.com/)
